block('promo-menu')(
    elem('menu').tag()('ul'),
    elem('item').tag()('li'),
    elem('link').tag()('a'),
    elem('number').tag()('span'),
    elem('link-text').tag()('span'),
    elem('title').tag()('span'),
    elem('description').tag()('span')
);
