[
    {
        title: 'MindBEMding – getting your head ’round BEM syntax',
        author: 'Harry Roberts',
        photo: 'promo-quotes__harry-roberts.jpg',
        position: 'Consultant Front-end Architect',
        url: 'http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/',
        text: 'I use BEM notation on everything I build now as its usefulness has proved itself over and over.',
    },
    {
        title: 'Maintainable CSS with BEM',
        author: 'Mark McDonnell',
        photo: 'promo-quotes__mark-mcdonnell.jpg',
        position: 'Technical Lead, BBC News',
        url: 'http://www.integralist.co.uk/posts/bem.html',
        text: 'Itʼs less confusing than the other methods (i.e. SMACSS) but still provides us the good architecture we want (i.e. OOCSS) and with a recognisable terminology.',
    },
    {
        title: 'Keeping the Front-End Modular with BEM',
        author: 'Connie Chan',
        photo: 'promo-quotes__connie-chan.jpg',
        position: 'Design Director, Thoughtbot',
        url: 'https://robots.thoughtbot.com/keeping-the-frontend-modular-with-bem',
        text: 'Combined with a preprocessor, BEM makes keeping your CSS modular and object-oriented a breeze.',
    },
    {
        title: 'BEM is okay',
        author: 'Vadim Makeev',
        photo: 'promo-quotes__vadim-makeev.jpg',
        position: 'Web Evangelist, Opera Software',
        url: 'http://pepelsbey.net/pres/bem-ok/en/',
        text: 'BEM is okay.',
    },
    {
        title: 'Q',
        author: 'Jonathan Snook',
        photo: 'promo-quotes__jonathan-snook.jpg',
        position: 'Author of OOCSS, Xero',
        url: 'https://twitter.com/snookca/status/606908589295464449',
        text: 'Most common misspelling is “SMACCS”. I should just reauthor it to BEM.',
    },
    {
        title: 'W',
        author: 'Paul Irish',
        photo: 'promo-quotes__paul-irish.jpg',
        position: 'Front-end Developer, Google Inc.',
        url: 'ttps://twitter.com/paul_irish/status/192483200696717312',
        text: 'This BEM stuff is next-level shit. Itʼs incredible how methodical it is.',
    },
    {
        title: 'E',
        author: 'Necolas Gallagher',
        photo: 'promo-quotes__necolas-gallagher.jpg',
        position: 'Software Engineer, Twitter',
        url: 'https://twitter.com/necolas/status/192678667023949824',
        text: 'BEM is far more than a HTML/CSS system. Iʼve got no plans to use it all; just adapted some of its ideas.',
    }
]
